steps:
- name: 'ubuntu'
  args: ['bash', 'cb_customBuild/custom-build-example2/myscript.bash','.']
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom-script-test', '.']
images: ['gcr.io/$PROJECT_ID/custom-script-test']


